# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the PCI specific kernel interface routines under Linux.
#

obj-y				+= pci.o
obj-$(CONFIG_ACPI)		+= acpi.o
obj-$(CONFIG_PCI_MMCONFIG)	+= mmconfig.o
obj-$(CONFIG_MACH_LOONGSON64)	+= pci-loongson.o
